### ISSUE TITLE
Not available in jcenter any more

### ISSUE THREAD

**Issue by psionic12** [aurae/RxBonjour#18]
I'v checked the jcenter and found out there's no RxBonjour any more, is there any other repositories available?

**Comment by mannodermaus** [comment]
Because of an issue with the automatic linking to jcenter, it seems like the old artifact is not available anymore. I'm still working on the 1.0.0 release, which is moving to a new artifact ID. In the meantime, you can add the Bintray repository directly, which allows the dependency to be pulled from there:

```groovy
allprojects {
    repositories {
        maven { url "https://dl.bintray.com/aurae/maven" }
    }
}
```

**Comment by mannodermaus** [comment]
The new version of the library has been released with new artifact IDs for RxJava 1 and 2, respectively. Please check the README for the new IDs!
